/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package sk.upjs.ics.kopr1;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.ObjectInputStream;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.Socket;
import java.util.Collections;
import java.util.HashSet;
import java.util.Scanner;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;

/**
 *
 * @author Michaela
 */
public class MainForm extends javax.swing.JFrame {
    
    /**
     * Creates new form MainForm
     */
    private Klient klient;
    private int pocetTCPspojeni;
    private Set<Long> precitaneOfesty;
    public MainForm() {
        initComponents();
        boloPrerusenie();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pocetTCPTextFiled = new javax.swing.JTextField();
        pocetTCPLabel = new javax.swing.JLabel();
        spustiButton = new javax.swing.JButton();
        prerusButton = new javax.swing.JButton();
        pokracujButton = new javax.swing.JButton();
        zrusitButton = new javax.swing.JButton();
        stahujemProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pocetTCPLabel.setText("Zadajte počet TCP spojení : ");

        spustiButton.setText("Spusiť");
        spustiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spustiButtonActionPerformed(evt);
            }
        });

        prerusButton.setText("Prerušiť");
        prerusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prerusButtonActionPerformed(evt);
            }
        });

        pokracujButton.setText("Pokračovať");
        pokracujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pokracujButtonActionPerformed(evt);
            }
        });

        zrusitButton.setText("Zrušiť");
        zrusitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zrusitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stahujemProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(spustiButton)
                        .addGap(34, 34, 34)
                        .addComponent(prerusButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(pokracujButton)
                        .addGap(26, 26, 26)
                        .addComponent(zrusitButton)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(pocetTCPLabel)
                .addGap(66, 66, 66)
                .addComponent(pocetTCPTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pocetTCPLabel)
                    .addComponent(pocetTCPTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(stahujemProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spustiButton)
                    .addComponent(prerusButton)
                    .addComponent(pokracujButton)
                    .addComponent(zrusitButton))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void spustiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spustiButtonActionPerformed
        klient= new Klient(Integer.parseInt(pocetTCPTextFiled.getText()), stahujemProgressBar);
        klient.spusti();
    }//GEN-LAST:event_spustiButtonActionPerformed
    
    private void prerusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prerusButtonActionPerformed
        if(klient!=null){
            klient.prerusit();
        }else{
            JOptionPane.showMessageDialog(this, "Nezačalo sa kopirovať!");
        }
    }//GEN-LAST:event_prerusButtonActionPerformed
    
    private void pokracujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pokracujButtonActionPerformed
        
        klient= new Klient(this);
        klient.pokracuj();
    }//GEN-LAST:event_pokracujButtonActionPerformed
    
    private void zrusitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zrusitButtonActionPerformed
        if(klient!=null){
            klient.zrusit();
            setVisible(false);
        }else{
            JOptionPane.showMessageDialog(this, "Nezačalo sa kopirovať!");
        }
    }//GEN-LAST:event_zrusitButtonActionPerformed
    
    
    private void boloPrerusenie(){
        
        File f= new File(Konstanty.ULOZ_SUBOR);
        if(f.exists() && f.length()>0){
             try {
                precitaneOfesty = Collections.synchronizedSet(new HashSet<Long>());
                Scanner sc= new Scanner(f);
                pocetTCPspojeni=Integer.parseInt(sc.next());
                while(sc.hasNext()){
                    long l =Long.parseLong(sc.next());
                    precitaneOfesty.add(l);
                }
                sc.close();
                int valueProgressBar= (int) (precitaneOfesty.size()*100.0/pocetTCPspojeni);
                stahujemProgressBar.setValue(valueProgressBar);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
   
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel pocetTCPLabel;
    private javax.swing.JTextField pocetTCPTextFiled;
    private javax.swing.JButton pokracujButton;
    private javax.swing.JButton prerusButton;
    private javax.swing.JButton spustiButton;
    private javax.swing.JProgressBar stahujemProgressBar;
    private javax.swing.JButton zrusitButton;
    // End of variables declaration//GEN-END:variables
}
